### ISSUE TITLE
Json deserialize error

### ISSUE THREAD

**Issue by ittokunvim** [ittokun/api-ittoku-tech#23]
# 概要

以下のパスに空のJSONデータ、もしくはデータを送らない場合に発生するエラー

- `POST /posts`
- `PATCH /posts/:id`

## 再現手順

以下のコマンドを実行して確認ください。

```bash
curl http://0.0.0.0:8080/posts -X POST -H "Content-Type: application/json"
# => Json deserialize error: EOF while parsing a value at line 1 column 0
curl http://0.0.0.0:8080/posts -X POST -H "Content-Type: application/json" -d '{}'
# => Json deserialize error: missing field `title` at line 1 column 2
```

## 現在の状況

再現手順の項目をご覧ください。

## 原因

ユーザーから送られるはずのJSONデータが送ってこない場合に発生するエラー。
つまり何も送ってこないユーザーからのリクエストがあった場合にserdeのエラーが起こる。

## 修正案

以下のURLを参考にバグの修正をお願いします。

https://serde.rs/error-handling.html

そして再現手順にあるコマンドを実行した際に返ってくるJSONを以下の通りにする。

```json
{
  "errors": [
    {
      "code": 422,
      "message": "body is required"
    },
    {
      "code": 422,
      "message": "title is required"
    }
  ]
}
```

**Comment by ittokunvim** [comment]
色々調べた結果、思い通りにはいかないっぽい。

https://github.com/actix/actix-web/issues/1163

上記のURL書かれている通りにやるとうまくいくっぽい。
つまり`serde deserialize error`が起こるケースに対するエラーレスポンスを返すといった感じ。

https://docs.rs/actix-web/latest/actix_web/web/struct.JsonConfig.html

`error_response`の実装は上記のURLを参考に行う。

また、JSONは下記のような感じで返す。

```json
{
  "message": "Post Data is Incorrect."
}
```

**Comment by shellking4** [comment]
how to be more specific in the error ? It would be good to reference the fields where the deserialization failed
